# Generated by Django 3.2.9 on 2021-11-18 16:39

from django.db import migrations

def create_data(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    Event(title="violin concerto", startDate="2021-09-05", endDate="2021-09-05").save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]